jobs:
- job: First Job Here
  pool:
    Name: Default
  steps:
  - script: echo Hello From Foo!
    condition: always() # this step will always run, even if cancelled

- job: Second Job and here
  pool:
    Name: Default
  dependsOn: Foo      # first wait for job Foo to complete
  condition: always() # this job will always run
  steps:
  - script: echo Hello From Bar!

- job: Job 3
  pool:
    Name: Default
  dependsOn: Bar      # first wait for job Foo to complete
  condition: always() # this job will always run
  steps:
  - script: echo Hello From Bar!